### ISSUE TITLE
Key Error in messages

### ISSUE THREAD

**Issue by shyamkanani** [abhishekchhibber/Gmail-Api-through-Python#2]
Traceback (most recent call last):
  File "c:\Users\MyHP\Desktop\New folder\gmail_read.py", line 53, in <module>
    mssg_list = unread_msgs['messages']
KeyError: 'messages'

**Comment by shanefolden** [comment]
how did you fix this?

**Comment by L422Y** [comment]
`
            if 'messages' in response:
                messages.extend(response['messages'])
`
